package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"

	"github.com/joho/godotenv"
	_ "github.com/lib/pq" // registers the postgres driver with database/sql
)

// Subscription mirrors a row in the subscriptions table.
type Subscription struct {
	ID        string
	Name      string
	Frequency string // "monthly" or "yearly"
	Status    string // "active" or "inactive"
	AutoRenew bool
}

func main() {
	// os.Args[0] is the program name; the command is os.Args[1].
	if len(os.Args) < 2 {
		fmt.Println("usage: go run . <command>")
		fmt.Println("commands: list, add <name> <frequency> <status> <auto_renew>, update <id> <name> <frequency> <status> <auto_renew>, delete <id>")
		os.Exit(1)
	}

	command := strings.ToLower(os.Args[1])

	dsn, err := loadDSN()
	if err != nil {
		log.Fatalf("load DSN: %v", err)
	}

	db, err := connectionDB(dsn)
	if err != nil {
		log.Fatalf("connect db: %v", err)
	}
	defer db.Close()

	switch command {
	case "list":
		subscriptions, err := listSubscriptions(db)
		if err != nil {
			log.Fatalf("list subscriptions: %v", err)
		}

		if len(subscriptions) == 0 {
			fmt.Println("No subscriptions found")
			return
		}

		for _, s := range subscriptions {
			fmt.Printf("%s | %s | %s | %s | auto_renew=%v\n", s.ID, s.Name, s.Frequency, s.Status, s.AutoRenew)
		}

	case "add":
		// Expected: add <name> <frequency> <status> <auto_renew>
		if len(os.Args) < 6 {
			fmt.Println("usage: go run . add <name> <frequency> <status> <auto_renew>")
			os.Exit(1)
		}

		name := os.Args[2]
		frequency := strings.ToLower(os.Args[3])
		status := strings.ToLower(os.Args[4])

		autoRenew, err := strconv.ParseBool(os.Args[5])
		if err != nil {
			log.Fatalf("auto_renew must be true or false: %v", err)
		}

		if err := addSubscription(db, name, frequency, status, autoRenew); err != nil {
			log.Fatalf("add subscription: %v", err)
		}

		fmt.Println("subscription added")

	case "update":
		// Expected: update <id> <name> <frequency> <status> <auto_renew>
		if len(os.Args) < 7 {
			fmt.Println("usage: go run . update <id> <name> <frequency> <status> <auto_renew>")
			os.Exit(1)
		}

		id := os.Args[2]
		name := os.Args[3]
		frequency := strings.ToLower(os.Args[4])
		status := strings.ToLower(os.Args[5])

		autoRenew, err := strconv.ParseBool(os.Args[6])
		if err != nil {
			log.Fatalf("auto_renew must be true or false: %v", err)
		}

		if err := updateSubscription(db, id, name, frequency, status, autoRenew); err != nil {
			log.Fatalf("update subscription: %v", err)
		}

		fmt.Println("subscription updated")

	case "delete":
		// Expected: delete <id>
		if len(os.Args) < 3 {
			fmt.Println("usage: go run . delete <id>")
			os.Exit(1)
		}

		id := os.Args[2]

		if err := deleteSubscription(db, id); err != nil {
			log.Fatalf("delete subscriptions: %v", err)
		}

		fmt.Println("subscription deleted")

	default:
		fmt.Printf("unknown command: %s\n", command)
		fmt.Println("commands: list, add <name> <frequency> <status> <auto_renew>, update <id> <name> <frequency> <status> <auto_renew>, delete <id>")
		os.Exit(1)
	}
}

// connectionDB opens a Postgres pool and verifies it with Ping.
// Caller is responsible for closing the returned *sql.DB.
func connectionDB(dsn string) (*sql.DB, error) {
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		return nil, fmt.Errorf("open db: %w", err)
	}

	// Open may succeed without contacting the server; Ping proves connectivity.
	if err := db.Ping(); err != nil {
		db.Close()
		return nil, fmt.Errorf("ping db: %w", err)
	}

	return db, nil
}

// loadDSN loads an optional local .env file, then reads DATABASE_URL.
// Missing .env is fine when the variable is already set in the environment.
func loadDSN() (string, error) {
	_ = godotenv.Load()

	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		return "", fmt.Errorf("DATABASE_URL is not set")
	}

	return dsn, nil
}

// listSubscriptions returns all subscriptions ordered by name.
// An empty table yields an empty (non-nil) slice, not an error.
func listSubscriptions(db *sql.DB) ([]Subscription, error) {
	rows, err := db.Query(`SELECT id, name, frequency, status, auto_renew FROM subscriptions ORDER BY name`)
	if err != nil {
		return nil, fmt.Errorf("list subscriptions: %w", err)
	}
	defer rows.Close()

	subscriptions := []Subscription{}

	for rows.Next() {
		var s Subscription
		// Scan column order must match the SELECT list above.
		if err := rows.Scan(&s.ID, &s.Name, &s.Frequency, &s.Status, &s.AutoRenew); err != nil {
			return nil, fmt.Errorf("scan subscription: %w", err)
		}
		subscriptions = append(subscriptions, s)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}

	return subscriptions, nil
}

// addSubscription inserts a new row. The id is generated by Postgres (DEFAULT gen_random_uuid()).
func addSubscription(db *sql.DB, name string, frequency string, status string, autoRenew bool) error {
	_, err := db.Exec(`INSERT INTO subscriptions (name, frequency, status, auto_renew) 
	VALUES ($1, $2, $3, $4)`, name, frequency, status, autoRenew)

	if err != nil {
		return fmt.Errorf("insert subscription: %w", err)
	}

	return nil
}

// updateSubscription replaces fields for the row with the given id.
// Returns an error if no row matches (RowsAffected == 0).
func updateSubscription(db *sql.DB, id string, name string, frequency string, status string, autoRenew bool) error {
	result, err := db.Exec(`UPDATE subscriptions SET name = $1, frequency = $2, status = $3, auto_renew = $4 WHERE id = $5`, name, frequency, status, autoRenew, id)
	if err != nil {
		return fmt.Errorf("update subscription: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("rows affected: %w", err)
	}

	if rowsAffected == 0 {
		return fmt.Errorf("subscription not found: %s", id)
	}

	return nil
}

// deleteSubscription removes the row with the given id.
// Returns an error if no row matches (RowsAffected == 0).
func deleteSubscription(db *sql.DB, id string) error {
	result, err := db.Exec(`DELETE FROM subscriptions WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("delete subscription: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("rows affected: %w", err)
	}

	if rowsAffected == 0 {
		return fmt.Errorf("subscription not found: %s", id)
	}

	return nil
}
